### ISSUE TITLE
Uncaught TypeError: resetTriggers is not a function

### ISSUE THREAD

**Issue by LendsMan** [sdecima/javascript-detect-element-resize#39]
I have an error in detect-element-resize.js after bundling my project with webpack. 
It seems like it's all about function declarations in conditional statement.

Check pull request https://github.com/sdecima/javascript-detect-element-resize/pull/40

**Comment by ssidorchik** [comment]
Also encountered this bug. Would be nice to have it fixed.

**Comment by marcfielding1** [comment]
Yeah can we fix this please, i'm encountering the same problem!

**Comment by marcfielding1** [comment]
Oh @LendsMan I think you'll also need to move the variable declarations outside the conditional too?

**Comment by jonataswalker** [comment]
It looks like this project is dead so I create a [new one](https://github.com/jonataswalker/watch-element-resize.js) based on this.

**Comment by LendsMan** [comment]
@jonataswalker let's just embrace mutation observer polyfill 🔧
